language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/phpunit

notifications:
  email: modx@agel-nash.ru
